language: python
addons:
  apt:
    packages:
    - libfftw3-dev
install:
- pip install --only-binary=numpy,scipy,cython,matplotlib numpy scipy cython matplotlib
- python setup.py install
script:
- cd tests
- nosetests
